---

- debug:
    msg: "The dbname is {{dbname}}"

- debug:
    var: dbuser

- name: Install mariadb-server
  ansible.builtin.yum:
    name: mariadb-server
    state: present

- name: Install pymysql
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: present

- name: Start mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{dbname}}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create a new database with username
  community.mysql.mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

  register: dboutput

- name: print dboutput variable
  debug:
    var: dboutput
